[project]
name = "langchain-yandex"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.13",
    "langchain-core>=0.3.68",
    "mypy>=1.16.1",
    "openai>=1.93.3",
    "ruff>=0.12.2",
]
